INCLUDEPATH *= $$PWD/uchardet/src
DEPENDPATH *= $$PWD/uchardet/src
HEADERS *= \
    $$PWD/uchardet/src/CharDistribution.h \
    $$PWD/uchardet/src/JpCntx.h \
    $$PWD/uchardet/src/nsBig5Prober.h \
    $$PWD/uchardet/src/nsCharSetProber.h \
    $$PWD/uchardet/src/nsCodingStateMachine.h \
    $$PWD/uchardet/src/nscore.h \
    $$PWD/uchardet/src/nsEscCharsetProber.h \
    $$PWD/uchardet/src/nsEUCJPProber.h \
    $$PWD/uchardet/src/nsEUCKRProber.h \
    $$PWD/uchardet/src/nsEUCTWProber.h \
    $$PWD/uchardet/src/nsGB2312Prober.h \
    $$PWD/uchardet/src/nsHebrewProber.h \
    $$PWD/uchardet/src/nsLatin1Prober.h \
    $$PWD/uchardet/src/nsMBCSGroupProber.h \
    $$PWD/uchardet/src/nsPkgInt.h \
    $$PWD/uchardet/src/nsSBCharSetProber.h \
    $$PWD/uchardet/src/nsSBCSGroupProber.h \
    $$PWD/uchardet/src/nsSJISProber.h \
    $$PWD/uchardet/src/nsUniversalDetector.h \
    $$PWD/uchardet/src/nsUTF8Prober.h \
    $$PWD/uchardet/src/prmem.h \
    $$PWD/uchardet/src/uchardet.h
SOURCES *= \
    $$PWD/uchardet/src/CharDistribution.cpp \
    $$PWD/uchardet/src/JpCntx.cpp \
    $$PWD/uchardet/src/nsBig5Prober.cpp \
    $$PWD/uchardet/src/nsCharSetProber.cpp \
    $$PWD/uchardet/src/nsEscCharsetProber.cpp \
    $$PWD/uchardet/src/nsEscSM.cpp \
    $$PWD/uchardet/src/nsEUCJPProber.cpp \
    $$PWD/uchardet/src/nsEUCKRProber.cpp \
    $$PWD/uchardet/src/nsEUCTWProber.cpp \
    $$PWD/uchardet/src/nsGB2312Prober.cpp \
    $$PWD/uchardet/src/nsHebrewProber.cpp \
    $$PWD/uchardet/src/nsLatin1Prober.cpp \
    $$PWD/uchardet/src/nsMBCSGroupProber.cpp \
    $$PWD/uchardet/src/nsMBCSSM.cpp \
    $$PWD/uchardet/src/nsSBCharSetProber.cpp \
    $$PWD/uchardet/src/nsSBCSGroupProber.cpp \
    $$PWD/uchardet/src/nsSJISProber.cpp \
    $$PWD/uchardet/src/nsUniversalDetector.cpp \
    $$PWD/uchardet/src/nsUTF8Prober.cpp \
    $$PWD/uchardet/src/uchardet.cpp \
    $$PWD/uchardet/src/LangModels/LangArabicModel.cpp \
    $$PWD/uchardet/src/LangModels/LangBulgarianModel.cpp \
    $$PWD/uchardet/src/LangModels/LangCroatianModel.cpp \
    $$PWD/uchardet/src/LangModels/LangCzechModel.cpp \
    $$PWD/uchardet/src/LangModels/LangDanishModel.cpp \
    $$PWD/uchardet/src/LangModels/LangEsperantoModel.cpp \
    $$PWD/uchardet/src/LangModels/LangEstonianModel.cpp \
    $$PWD/uchardet/src/LangModels/LangFinnishModel.cpp \
    $$PWD/uchardet/src/LangModels/LangFrenchModel.cpp \
    $$PWD/uchardet/src/LangModels/LangGermanModel.cpp \
    $$PWD/uchardet/src/LangModels/LangGreekModel.cpp \
    $$PWD/uchardet/src/LangModels/LangHebrewModel.cpp \
    $$PWD/uchardet/src/LangModels/LangHungarianModel.cpp \
    $$PWD/uchardet/src/LangModels/LangIrishModel.cpp \
    $$PWD/uchardet/src/LangModels/LangItalianModel.cpp \
    $$PWD/uchardet/src/LangModels/LangLatvianModel.cpp \
    $$PWD/uchardet/src/LangModels/LangLithuanianModel.cpp \
    $$PWD/uchardet/src/LangModels/LangMalteseModel.cpp \
    $$PWD/uchardet/src/LangModels/LangPolishModel.cpp \
    $$PWD/uchardet/src/LangModels/LangPortugueseModel.cpp \
    $$PWD/uchardet/src/LangModels/LangRomanianModel.cpp \
    $$PWD/uchardet/src/LangModels/LangRussianModel.cpp \
    $$PWD/uchardet/src/LangModels/LangSlovakModel.cpp \
    $$PWD/uchardet/src/LangModels/LangSloveneModel.cpp \
    $$PWD/uchardet/src/LangModels/LangSpanishModel.cpp \
    $$PWD/uchardet/src/LangModels/LangSwedishModel.cpp \
    $$PWD/uchardet/src/LangModels/LangThaiModel.cpp \
    $$PWD/uchardet/src/LangModels/LangTurkishModel.cpp \
    $$PWD/uchardet/src/LangModels/LangVietnameseModel.cpp
